# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  storageClassName: es-cloud-ssd-pv-jenkins
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 66Gi
---
# How do we want it implemented
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: es-cloud-ssd-pv-jenkins
  namespace: jenkins
reclaimPolicy: Retain
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
